
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package shtundex.init;

import shtundex.item.TreasureBag2Item;
import shtundex.item.TreasureBag1Item;
import shtundex.item.TheStickItem;
import shtundex.item.TestEmptyItem;
import shtundex.item.SwordlandItem;
import shtundex.item.ShtuxiteSoulItem;
import shtundex.item.ShtuxiteBlasterItem;
import shtundex.item.ShtuxianHandleItem;
import shtundex.item.ShtuxianEnergyItem;
import shtundex.item.ShtuxianCurseItem;
import shtundex.item.ShtuxSwordItem;
import shtundex.item.ShtuxStaffOfPowerItem;
import shtundex.item.ShtundexWorldItem;
import shtundex.item.ShtundexWorldBlessingItem;
import shtundex.item.ShtunderPrismItem;
import shtundex.item.ShtunStoneSwordItem;
import shtundex.item.ShtunStoneShovelItem;
import shtundex.item.ShtunStonePickaxeItem;
import shtundex.item.ShtunStoneHoeItem;
import shtundex.item.ShtunStoneAxeItem;
import shtundex.item.ShtukCyberneticPartsItem;
import shtundex.item.RechargerItem;
import shtundex.item.PlatePressItem;
import shtundex.item.NetheriteGearItem;
import shtundex.item.NetherStarStaffItem;
import shtundex.item.MoltenCatsteelItem;
import shtundex.item.LoreShtuxibusItem;
import shtundex.item.LoreShtundexWorldItem;
import shtundex.item.LoreShtq7v3Item;
import shtundex.item.LoreChtuxlagorItem;
import shtundex.item.LoreCatsteelItem;
import shtundex.item.KotiumItem;
import shtundex.item.HumanCellsItem;
import shtundex.item.FlourItem;
import shtundex.item.EmptySyrgineItem;
import shtundex.item.CursedCatsteelMechanismItem;
import shtundex.item.CoinPressSchemeItem;
import shtundex.item.ClothItem;
import shtundex.item.ChtuxlagorShardItem;
import shtundex.item.ChtuxlagorPieceItem;
import shtundex.item.ChtuxlagorBlessingCuriosItem;
import shtundex.item.ChtuxlagorBlasterItem;
import shtundex.item.CatsteelSwordItem;
import shtundex.item.CatsteelShovelItem;
import shtundex.item.CatsteelPlateItem;
import shtundex.item.CatsteelPickaxeItem;
import shtundex.item.CatsteelNuggetItem;
import shtundex.item.CatsteelDrillHeadItem;
import shtundex.item.CatsteelDrillHandleItem;
import shtundex.item.CatsteelCoinItem;
import shtundex.item.CatsteelBladeItem;
import shtundex.item.CatsteelBarItem;
import shtundex.item.CatsteelAxeItem;
import shtundex.item.CatsteelArmorItem;
import shtundex.item.CatsteelAppleItem;
import shtundex.item.CatSteelDrillItem;
import shtundex.item.CatClothItem;
import shtundex.item.CatClotArmorItem;
import shtundex.item.CATHightTechSuitItem;
import shtundex.item.BerryPieItem;
import shtundex.item.AdvancedShtukPartsItem;

import shtundex.ShtundexMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

public class ShtundexModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, ShtundexMod.MODID);
	public static final RegistryObject<Item> SHTUXIAN_CURSE = REGISTRY.register("shtuxian_curse", () -> new ShtuxianCurseItem());
	public static final RegistryObject<Item> CAT_HIGHT_TECH_SUIT_HELMET = REGISTRY.register("cat_hight_tech_suit_helmet", () -> new CATHightTechSuitItem.Helmet());
	public static final RegistryObject<Item> CAT_HIGHT_TECH_SUIT_CHESTPLATE = REGISTRY.register("cat_hight_tech_suit_chestplate", () -> new CATHightTechSuitItem.Chestplate());
	public static final RegistryObject<Item> CAT_HIGHT_TECH_SUIT_LEGGINGS = REGISTRY.register("cat_hight_tech_suit_leggings", () -> new CATHightTechSuitItem.Leggings());
	public static final RegistryObject<Item> CAT_HIGHT_TECH_SUIT_BOOTS = REGISTRY.register("cat_hight_tech_suit_boots", () -> new CATHightTechSuitItem.Boots());
	public static final RegistryObject<Item> CATSTEEL_BAR = REGISTRY.register("catsteel_bar", () -> new CatsteelBarItem());
	public static final RegistryObject<Item> SHTUNDER_PRISM = REGISTRY.register("shtunder_prism", () -> new ShtunderPrismItem());
	public static final RegistryObject<Item> CAT_CLOTH = REGISTRY.register("cat_cloth", () -> new CatClothItem());
	public static final RegistryObject<Item> CAT_CLOT_ARMOR_HELMET = REGISTRY.register("cat_clot_armor_helmet", () -> new CatClotArmorItem.Helmet());
	public static final RegistryObject<Item> CAT_CLOT_ARMOR_CHESTPLATE = REGISTRY.register("cat_clot_armor_chestplate", () -> new CatClotArmorItem.Chestplate());
	public static final RegistryObject<Item> CAT_CLOT_ARMOR_LEGGINGS = REGISTRY.register("cat_clot_armor_leggings", () -> new CatClotArmorItem.Leggings());
	public static final RegistryObject<Item> CAT_CLOT_ARMOR_BOOTS = REGISTRY.register("cat_clot_armor_boots", () -> new CatClotArmorItem.Boots());
	public static final RegistryObject<Item> SHTUXIAN_ENERGY = REGISTRY.register("shtuxian_energy", () -> new ShtuxianEnergyItem());
	public static final RegistryObject<Item> KOTIUM = REGISTRY.register("kotium", () -> new KotiumItem());
	public static final RegistryObject<Item> CATSTEEL_ORE = block(ShtundexModBlocks.CATSTEEL_ORE);
	public static final RegistryObject<Item> SHTUNDEX_WORLD = REGISTRY.register("shtundex_world", () -> new ShtundexWorldItem());
	public static final RegistryObject<Item> CLOTH = REGISTRY.register("cloth", () -> new ClothItem());
	public static final RegistryObject<Item> THE_STICK = REGISTRY.register("the_stick", () -> new TheStickItem());
	public static final RegistryObject<Item> SHTUXIAN_HANDLE = REGISTRY.register("shtuxian_handle", () -> new ShtuxianHandleItem());
	public static final RegistryObject<Item> CATSTEEL_BLADE = REGISTRY.register("catsteel_blade", () -> new CatsteelBladeItem());
	public static final RegistryObject<Item> SHTUXITE_BLASTER = REGISTRY.register("shtuxite_blaster", () -> new ShtuxiteBlasterItem());
	public static final RegistryObject<Item> CURSED_CATSTEEL_MECHANISM = REGISTRY.register("cursed_catsteel_mechanism", () -> new CursedCatsteelMechanismItem());
	public static final RegistryObject<Item> NETHERITE_GEAR = REGISTRY.register("netherite_gear", () -> new NetheriteGearItem());
	public static final RegistryObject<Item> CATSTEEL_ARMOR_HELMET = REGISTRY.register("catsteel_armor_helmet", () -> new CatsteelArmorItem.Helmet());
	public static final RegistryObject<Item> CATSTEEL_ARMOR_CHESTPLATE = REGISTRY.register("catsteel_armor_chestplate", () -> new CatsteelArmorItem.Chestplate());
	public static final RegistryObject<Item> CATSTEEL_ARMOR_LEGGINGS = REGISTRY.register("catsteel_armor_leggings", () -> new CatsteelArmorItem.Leggings());
	public static final RegistryObject<Item> CATSTEEL_ARMOR_BOOTS = REGISTRY.register("catsteel_armor_boots", () -> new CatsteelArmorItem.Boots());
	public static final RegistryObject<Item> CATSTEEL_PLATE = REGISTRY.register("catsteel_plate", () -> new CatsteelPlateItem());
	public static final RegistryObject<Item> SHTUX_SWORD = REGISTRY.register("shtux_sword", () -> new ShtuxSwordItem());
	public static final RegistryObject<Item> TEST_EMPTY = REGISTRY.register("test_empty", () -> new TestEmptyItem());
	public static final RegistryObject<Item> NETHER_STAR_STAFF = REGISTRY.register("nether_star_staff", () -> new NetherStarStaffItem());
	public static final RegistryObject<Item> CAT_STEEL_DRILL = REGISTRY.register("cat_steel_drill", () -> new CatSteelDrillItem());
	public static final RegistryObject<Item> SHTUX_STAFF_OF_POWER = REGISTRY.register("shtux_staff_of_power", () -> new ShtuxStaffOfPowerItem());
	public static final RegistryObject<Item> SHTUK_CYBERNETIC_PARTS = REGISTRY.register("shtuk_cybernetic_parts", () -> new ShtukCyberneticPartsItem());
	public static final RegistryObject<Item> HUMAN_CELLS = REGISTRY.register("human_cells", () -> new HumanCellsItem());
	public static final RegistryObject<Item> EMPTY_SYRGINE = REGISTRY.register("empty_syrgine", () -> new EmptySyrgineItem());
	public static final RegistryObject<Item> TREASURE_BAG_1 = REGISTRY.register("treasure_bag_1", () -> new TreasureBag1Item());
	public static final RegistryObject<Item> TREASURE_BAG_2 = REGISTRY.register("treasure_bag_2", () -> new TreasureBag2Item());
	public static final RegistryObject<Item> RECHARGER = REGISTRY.register("recharger", () -> new RechargerItem());
	public static final RegistryObject<Item> ADVANCED_SHTUK_PARTS = REGISTRY.register("advanced_shtuk_parts", () -> new AdvancedShtukPartsItem());
	public static final RegistryObject<Item> CATSTEEL_DRILL_HEAD = REGISTRY.register("catsteel_drill_head", () -> new CatsteelDrillHeadItem());
	public static final RegistryObject<Item> CATSTEEL_DRILL_HANDLE = REGISTRY.register("catsteel_drill_handle", () -> new CatsteelDrillHandleItem());
	public static final RegistryObject<Item> CHTUXLAGOR_BLASTER = REGISTRY.register("chtuxlagor_blaster", () -> new ChtuxlagorBlasterItem());
	public static final RegistryObject<Item> CHTUXLAGOR_SHARD = REGISTRY.register("chtuxlagor_shard", () -> new ChtuxlagorShardItem());
	public static final RegistryObject<Item> LORE_CATSTEEL = REGISTRY.register("lore_catsteel", () -> new LoreCatsteelItem());
	public static final RegistryObject<Item> LORE_SHTUXIBUS = REGISTRY.register("lore_shtuxibus", () -> new LoreShtuxibusItem());
	public static final RegistryObject<Item> LORE_CHTUXLAGOR = REGISTRY.register("lore_chtuxlagor", () -> new LoreChtuxlagorItem());
	public static final RegistryObject<Item> LORE_SHTUNDEX_WORLD = REGISTRY.register("lore_shtundex_world", () -> new LoreShtundexWorldItem());
	public static final RegistryObject<Item> SHTUNDEX_STONE = block(ShtundexModBlocks.SHTUNDEX_STONE);
	public static final RegistryObject<Item> ALPHALT = block(ShtundexModBlocks.ALPHALT);
	public static final RegistryObject<Item> MOLTEN_CATSTEEL_BUCKET = REGISTRY.register("molten_catsteel_bucket", () -> new MoltenCatsteelItem());
	public static final RegistryObject<Item> SHTUN_STONE_PICKAXE = REGISTRY.register("shtun_stone_pickaxe", () -> new ShtunStonePickaxeItem());
	public static final RegistryObject<Item> SHTUN_STONE_AXE = REGISTRY.register("shtun_stone_axe", () -> new ShtunStoneAxeItem());
	public static final RegistryObject<Item> SHTUN_STONE_SWORD = REGISTRY.register("shtun_stone_sword", () -> new ShtunStoneSwordItem());
	public static final RegistryObject<Item> SHTUN_STONE_SHOVEL = REGISTRY.register("shtun_stone_shovel", () -> new ShtunStoneShovelItem());
	public static final RegistryObject<Item> SHTUN_STONE_HOE = REGISTRY.register("shtun_stone_hoe", () -> new ShtunStoneHoeItem());
	public static final RegistryObject<Item> CATSTEEL_PICKAXE = REGISTRY.register("catsteel_pickaxe", () -> new CatsteelPickaxeItem());
	public static final RegistryObject<Item> CATSTEEL_AXE = REGISTRY.register("catsteel_axe", () -> new CatsteelAxeItem());
	public static final RegistryObject<Item> CATSTEEL_SWORD = REGISTRY.register("catsteel_sword", () -> new CatsteelSwordItem());
	public static final RegistryObject<Item> CATSTEEL_SHOVEL = REGISTRY.register("catsteel_shovel", () -> new CatsteelShovelItem());
	public static final RegistryObject<Item> SHTUXITE_SOUL = REGISTRY.register("shtuxite_soul", () -> new ShtuxiteSoulItem());
	public static final RegistryObject<Item> LORE_SHTQ_7V_3 = REGISTRY.register("lore_shtq_7v_3", () -> new LoreShtq7v3Item());
	public static final RegistryObject<Item> CHTUXLAGOR_PIECE = REGISTRY.register("chtuxlagor_piece", () -> new ChtuxlagorPieceItem());
	public static final RegistryObject<Item> CATSTEEL_BLOCK = block(ShtundexModBlocks.CATSTEEL_BLOCK);
	public static final RegistryObject<Item> BERRY_PIE = REGISTRY.register("berry_pie", () -> new BerryPieItem());
	public static final RegistryObject<Item> FLOUR = REGISTRY.register("flour", () -> new FlourItem());
	public static final RegistryObject<Item> CATSTEEL_APPLE = REGISTRY.register("catsteel_apple", () -> new CatsteelAppleItem());
	public static final RegistryObject<Item> CATSTEEL_COIN = REGISTRY.register("catsteel_coin", () -> new CatsteelCoinItem());
	public static final RegistryObject<Item> CRATE = block(ShtundexModBlocks.CRATE);
	public static final RegistryObject<Item> COIN_PRESS_SCHEME = REGISTRY.register("coin_press_scheme", () -> new CoinPressSchemeItem());
	public static final RegistryObject<Item> CATSTEEL_NUGGET = REGISTRY.register("catsteel_nugget", () -> new CatsteelNuggetItem());
	public static final RegistryObject<Item> SWORDLAND = REGISTRY.register("swordland", () -> new SwordlandItem());
	public static final RegistryObject<Item> CHTUXLAGOR_BLESSING_CURIOS = REGISTRY.register("chtuxlagor_blessing_curios", () -> new ChtuxlagorBlessingCuriosItem());
	public static final RegistryObject<Item> SHTUNDEX_WORLD_BLESSING = REGISTRY.register("shtundex_world_blessing", () -> new ShtundexWorldBlessingItem());
	public static final RegistryObject<Item> PLATE_PRESS = REGISTRY.register("plate_press", () -> new PlatePressItem());
	public static final RegistryObject<Item> PRESS = block(ShtundexModBlocks.PRESS);
	public static final RegistryObject<Item> CATSTEEL_WORKBENCH_BLOCK = block(ShtundexModBlocks.CATSTEEL_WORKBENCH_BLOCK);

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
