
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package shtundex.init;

import shtundex.item.XenomiteShardItem;
import shtundex.item.WrenchItem;
import shtundex.item.WarpedSwordItem;
import shtundex.item.WarpedShovelItem;
import shtundex.item.WarpedPickaxeItem;
import shtundex.item.WarpedIngotItem;
import shtundex.item.WarpedForceItem;
import shtundex.item.WarpedAxeItem;
import shtundex.item.WarpedArmorItem;
import shtundex.item.VampiricAmuletItem;
import shtundex.item.UraniumIngotItem;
import shtundex.item.UraniumDustItem;
import shtundex.item.UnfinishedNetheriteCircuitItem;
import shtundex.item.UnfinishedCatsteelCircuitItem;
import shtundex.item.TrerraformingDirtStaffItem;
import shtundex.item.TreasureBag2Item;
import shtundex.item.TreasureBag1Item;
import shtundex.item.TravelerBootsItem;
import shtundex.item.TinyChtuxlagorShardItem;
import shtundex.item.TinIngotItem;
import shtundex.item.TinForceItem;
import shtundex.item.TinDustItem;
import shtundex.item.TheStickItem;
import shtundex.item.TestEmptyItem;
import shtundex.item.SwordlandItem;
import shtundex.item.ShtuxiteSoulItem;
import shtundex.item.ShtuxiteBlasterItem;
import shtundex.item.ShtuxibusForceItem;
import shtundex.item.ShtuxianKitItem;
import shtundex.item.ShtuxianHandleItem;
import shtundex.item.ShtuxianEnergyItem;
import shtundex.item.ShtuxianCurseItem;
import shtundex.item.ShtuxSwordItem;
import shtundex.item.ShtuxStaffOfPowerItem;
import shtundex.item.ShtundexWorldItem;
import shtundex.item.ShtundexWorldBlessingItem;
import shtundex.item.ShtunderPrismItem;
import shtundex.item.ShtunStoneSwordItem;
import shtundex.item.ShtunStoneShovelItem;
import shtundex.item.ShtunStonePickaxeItem;
import shtundex.item.ShtunStoneHoeItem;
import shtundex.item.ShtunStoneAxeItem;
import shtundex.item.ShtukCyberneticPartsItem;
import shtundex.item.ShtQ7ForceItem;
import shtundex.item.RefinedXeniumPlateItem;
import shtundex.item.RechargerItem;
import shtundex.item.RawUraniumItem;
import shtundex.item.RawTinItem;
import shtundex.item.RawLeadItem;
import shtundex.item.PlatePressItem;
import shtundex.item.PizzaItem;
import shtundex.item.PizzaBoxItem;
import shtundex.item.ObsidianDustItem;
import shtundex.item.NetheriteGearTrueItem;
import shtundex.item.NetheriteGearItem;
import shtundex.item.NetheriteForceItem;
import shtundex.item.NetheriteCircuitItem;
import shtundex.item.NetherStarStaffItem;
import shtundex.item.NanosaberItem;
import shtundex.item.NanosaberActiveItem;
import shtundex.item.NanofiberClothItem;
import shtundex.item.NanoItem;
import shtundex.item.MoltenCatsteelItem;
import shtundex.item.MinerForceItem;
import shtundex.item.MaterialForceItem;
import shtundex.item.LoreShtuxibusItem;
import shtundex.item.LoreShtundexWorldItem;
import shtundex.item.LoreShtq7v3Item;
import shtundex.item.LoreChtuxlagorItem;
import shtundex.item.LoreCatsteelItem;
import shtundex.item.LoreAwakeningItem;
import shtundex.item.LeadPlateItem;
import shtundex.item.LeadIngotItem;
import shtundex.item.LeadDustItem;
import shtundex.item.LapisForceItem;
import shtundex.item.KotiumItem;
import shtundex.item.IronGearItem;
import shtundex.item.IronDustItem;
import shtundex.item.InfinityModeChangerItem;
import shtundex.item.HumanCellsItem;
import shtundex.item.HazmatItem;
import shtundex.item.GrindingBallItem;
import shtundex.item.GoldenForceItem;
import shtundex.item.GoldDustItem;
import shtundex.item.GeigerCountItem;
import shtundex.item.FlourItem;
import shtundex.item.EnergyCrystalItem;
import shtundex.item.EmptySyrgineItem;
import shtundex.item.EmeraldForceItem;
import shtundex.item.DiamondForceItem;
import shtundex.item.DiamondDustItem;
import shtundex.item.DepelletedCatsteelItem;
import shtundex.item.DarkSwordItem;
import shtundex.item.DarkSteelIngotItem;
import shtundex.item.DarkSteelDustItem;
import shtundex.item.DarkPickaxeItem;
import shtundex.item.DarkAxeItem;
import shtundex.item.DarkArmorItem;
import shtundex.item.CursedCatsteelMechanismItem;
import shtundex.item.CrimsonSwordItem;
import shtundex.item.CrimsonShovelItem;
import shtundex.item.CrimsonPickaxeItem;
import shtundex.item.CrimsonIngotItem;
import shtundex.item.CrimsonForceItem;
import shtundex.item.CrimsonAxeItem;
import shtundex.item.CrimsonArmorItem;
import shtundex.item.CopperForceItem;
import shtundex.item.CopperDustItem;
import shtundex.item.CoinPressSchemeItem;
import shtundex.item.CoalDustItem;
import shtundex.item.ClothItem;
import shtundex.item.CircuitPrsssItem;
import shtundex.item.CircuitItem;
import shtundex.item.ChtuxlagorShardItem;
import shtundex.item.ChtuxlagorPieceItem;
import shtundex.item.ChtuxlagorMantleItem;
import shtundex.item.ChtuxlagorKitItem;
import shtundex.item.ChtuxlagorForceItem;
import shtundex.item.ChtuxlagorBlessingCuriosItem;
import shtundex.item.ChtuxlagorBlasterItem;
import shtundex.item.ChalkItem;
import shtundex.item.CatsteelSwordItem;
import shtundex.item.CatsteelStimulantsItem;
import shtundex.item.CatsteelStaffItem;
import shtundex.item.CatsteelShovelItem;
import shtundex.item.CatsteelShieldItem;
import shtundex.item.CatsteelRingItem;
import shtundex.item.CatsteelPlateItem;
import shtundex.item.CatsteelPillItem;
import shtundex.item.CatsteelPickaxeItem;
import shtundex.item.CatsteelNuggetItem;
import shtundex.item.CatsteelForceItem;
import shtundex.item.CatsteelDustItem;
import shtundex.item.CatsteelDrillHeadItem;
import shtundex.item.CatsteelDrillHandleItem;
import shtundex.item.CatsteelCoinItem;
import shtundex.item.CatsteelBladeItem;
import shtundex.item.CatsteelBarItem;
import shtundex.item.CatsteelAxeItem;
import shtundex.item.CatsteelArmorItem;
import shtundex.item.CatsteelAppleItem;
import shtundex.item.CatSteelDrillItem;
import shtundex.item.CatCoreItem;
import shtundex.item.CatClothItem;
import shtundex.item.CatClotArmorItem;
import shtundex.item.CATHightTechSuitItem;
import shtundex.item.BronzeIngotItem;
import shtundex.item.BronzeDustItem;
import shtundex.item.BerryPieItem;
import shtundex.item.ArmorRechargeModuleItem;
import shtundex.item.AntiradClothItem;
import shtundex.item.AdvancedShtukPartsItem;

import shtundex.ShtundexMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

public class ShtundexModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, ShtundexMod.MODID);
	public static final RegistryObject<Item> SHTUXIAN_CURSE = REGISTRY.register("shtuxian_curse", () -> new ShtuxianCurseItem());
	public static final RegistryObject<Item> CAT_HIGHT_TECH_SUIT_HELMET = REGISTRY.register("cat_hight_tech_suit_helmet", () -> new CATHightTechSuitItem.Helmet());
	public static final RegistryObject<Item> CAT_HIGHT_TECH_SUIT_CHESTPLATE = REGISTRY.register("cat_hight_tech_suit_chestplate", () -> new CATHightTechSuitItem.Chestplate());
	public static final RegistryObject<Item> CAT_HIGHT_TECH_SUIT_LEGGINGS = REGISTRY.register("cat_hight_tech_suit_leggings", () -> new CATHightTechSuitItem.Leggings());
	public static final RegistryObject<Item> CAT_HIGHT_TECH_SUIT_BOOTS = REGISTRY.register("cat_hight_tech_suit_boots", () -> new CATHightTechSuitItem.Boots());
	public static final RegistryObject<Item> CATSTEEL_BAR = REGISTRY.register("catsteel_bar", () -> new CatsteelBarItem());
	public static final RegistryObject<Item> SHTUNDER_PRISM = REGISTRY.register("shtunder_prism", () -> new ShtunderPrismItem());
	public static final RegistryObject<Item> CAT_CLOTH = REGISTRY.register("cat_cloth", () -> new CatClothItem());
	public static final RegistryObject<Item> CAT_CLOT_ARMOR_HELMET = REGISTRY.register("cat_clot_armor_helmet", () -> new CatClotArmorItem.Helmet());
	public static final RegistryObject<Item> CAT_CLOT_ARMOR_CHESTPLATE = REGISTRY.register("cat_clot_armor_chestplate", () -> new CatClotArmorItem.Chestplate());
	public static final RegistryObject<Item> CAT_CLOT_ARMOR_LEGGINGS = REGISTRY.register("cat_clot_armor_leggings", () -> new CatClotArmorItem.Leggings());
	public static final RegistryObject<Item> CAT_CLOT_ARMOR_BOOTS = REGISTRY.register("cat_clot_armor_boots", () -> new CatClotArmorItem.Boots());
	public static final RegistryObject<Item> SHTUXIAN_ENERGY = REGISTRY.register("shtuxian_energy", () -> new ShtuxianEnergyItem());
	public static final RegistryObject<Item> KOTIUM = REGISTRY.register("kotium", () -> new KotiumItem());
	public static final RegistryObject<Item> CATSTEEL_ORE = block(ShtundexModBlocks.CATSTEEL_ORE);
	public static final RegistryObject<Item> SHTUNDEX_WORLD = REGISTRY.register("shtundex_world", () -> new ShtundexWorldItem());
	public static final RegistryObject<Item> CLOTH = REGISTRY.register("cloth", () -> new ClothItem());
	public static final RegistryObject<Item> THE_STICK = REGISTRY.register("the_stick", () -> new TheStickItem());
	public static final RegistryObject<Item> SHTUXIAN_HANDLE = REGISTRY.register("shtuxian_handle", () -> new ShtuxianHandleItem());
	public static final RegistryObject<Item> CATSTEEL_BLADE = REGISTRY.register("catsteel_blade", () -> new CatsteelBladeItem());
	public static final RegistryObject<Item> SHTUXITE_BLASTER = REGISTRY.register("shtuxite_blaster", () -> new ShtuxiteBlasterItem());
	public static final RegistryObject<Item> CURSED_CATSTEEL_MECHANISM = REGISTRY.register("cursed_catsteel_mechanism", () -> new CursedCatsteelMechanismItem());
	public static final RegistryObject<Item> NETHERITE_GEAR = REGISTRY.register("netherite_gear", () -> new NetheriteGearItem());
	public static final RegistryObject<Item> CATSTEEL_ARMOR_HELMET = REGISTRY.register("catsteel_armor_helmet", () -> new CatsteelArmorItem.Helmet());
	public static final RegistryObject<Item> CATSTEEL_ARMOR_CHESTPLATE = REGISTRY.register("catsteel_armor_chestplate", () -> new CatsteelArmorItem.Chestplate());
	public static final RegistryObject<Item> CATSTEEL_ARMOR_LEGGINGS = REGISTRY.register("catsteel_armor_leggings", () -> new CatsteelArmorItem.Leggings());
	public static final RegistryObject<Item> CATSTEEL_ARMOR_BOOTS = REGISTRY.register("catsteel_armor_boots", () -> new CatsteelArmorItem.Boots());
	public static final RegistryObject<Item> CATSTEEL_PLATE = REGISTRY.register("catsteel_plate", () -> new CatsteelPlateItem());
	public static final RegistryObject<Item> SHTUX_SWORD = REGISTRY.register("shtux_sword", () -> new ShtuxSwordItem());
	public static final RegistryObject<Item> TEST_EMPTY = REGISTRY.register("test_empty", () -> new TestEmptyItem());
	public static final RegistryObject<Item> NETHER_STAR_STAFF = REGISTRY.register("nether_star_staff", () -> new NetherStarStaffItem());
	public static final RegistryObject<Item> CAT_STEEL_DRILL = REGISTRY.register("cat_steel_drill", () -> new CatSteelDrillItem());
	public static final RegistryObject<Item> SHTUX_STAFF_OF_POWER = REGISTRY.register("shtux_staff_of_power", () -> new ShtuxStaffOfPowerItem());
	public static final RegistryObject<Item> SHTUK_CYBERNETIC_PARTS = REGISTRY.register("shtuk_cybernetic_parts", () -> new ShtukCyberneticPartsItem());
	public static final RegistryObject<Item> HUMAN_CELLS = REGISTRY.register("human_cells", () -> new HumanCellsItem());
	public static final RegistryObject<Item> EMPTY_SYRGINE = REGISTRY.register("empty_syrgine", () -> new EmptySyrgineItem());
	public static final RegistryObject<Item> TREASURE_BAG_1 = REGISTRY.register("treasure_bag_1", () -> new TreasureBag1Item());
	public static final RegistryObject<Item> TREASURE_BAG_2 = REGISTRY.register("treasure_bag_2", () -> new TreasureBag2Item());
	public static final RegistryObject<Item> RECHARGER = REGISTRY.register("recharger", () -> new RechargerItem());
	public static final RegistryObject<Item> ADVANCED_SHTUK_PARTS = REGISTRY.register("advanced_shtuk_parts", () -> new AdvancedShtukPartsItem());
	public static final RegistryObject<Item> CATSTEEL_DRILL_HEAD = REGISTRY.register("catsteel_drill_head", () -> new CatsteelDrillHeadItem());
	public static final RegistryObject<Item> CATSTEEL_DRILL_HANDLE = REGISTRY.register("catsteel_drill_handle", () -> new CatsteelDrillHandleItem());
	public static final RegistryObject<Item> CHTUXLAGOR_BLASTER = REGISTRY.register("chtuxlagor_blaster", () -> new ChtuxlagorBlasterItem());
	public static final RegistryObject<Item> CHTUXLAGOR_SHARD = REGISTRY.register("chtuxlagor_shard", () -> new ChtuxlagorShardItem());
	public static final RegistryObject<Item> LORE_CATSTEEL = REGISTRY.register("lore_catsteel", () -> new LoreCatsteelItem());
	public static final RegistryObject<Item> LORE_SHTUXIBUS = REGISTRY.register("lore_shtuxibus", () -> new LoreShtuxibusItem());
	public static final RegistryObject<Item> LORE_CHTUXLAGOR = REGISTRY.register("lore_chtuxlagor", () -> new LoreChtuxlagorItem());
	public static final RegistryObject<Item> LORE_SHTUNDEX_WORLD = REGISTRY.register("lore_shtundex_world", () -> new LoreShtundexWorldItem());
	public static final RegistryObject<Item> SHTUNDEX_STONE = block(ShtundexModBlocks.SHTUNDEX_STONE);
	public static final RegistryObject<Item> ALPHALT = block(ShtundexModBlocks.ALPHALT);
	public static final RegistryObject<Item> MOLTEN_CATSTEEL_BUCKET = REGISTRY.register("molten_catsteel_bucket", () -> new MoltenCatsteelItem());
	public static final RegistryObject<Item> SHTUN_STONE_PICKAXE = REGISTRY.register("shtun_stone_pickaxe", () -> new ShtunStonePickaxeItem());
	public static final RegistryObject<Item> SHTUN_STONE_AXE = REGISTRY.register("shtun_stone_axe", () -> new ShtunStoneAxeItem());
	public static final RegistryObject<Item> SHTUN_STONE_SWORD = REGISTRY.register("shtun_stone_sword", () -> new ShtunStoneSwordItem());
	public static final RegistryObject<Item> SHTUN_STONE_SHOVEL = REGISTRY.register("shtun_stone_shovel", () -> new ShtunStoneShovelItem());
	public static final RegistryObject<Item> SHTUN_STONE_HOE = REGISTRY.register("shtun_stone_hoe", () -> new ShtunStoneHoeItem());
	public static final RegistryObject<Item> CATSTEEL_PICKAXE = REGISTRY.register("catsteel_pickaxe", () -> new CatsteelPickaxeItem());
	public static final RegistryObject<Item> CATSTEEL_AXE = REGISTRY.register("catsteel_axe", () -> new CatsteelAxeItem());
	public static final RegistryObject<Item> CATSTEEL_SWORD = REGISTRY.register("catsteel_sword", () -> new CatsteelSwordItem());
	public static final RegistryObject<Item> CATSTEEL_SHOVEL = REGISTRY.register("catsteel_shovel", () -> new CatsteelShovelItem());
	public static final RegistryObject<Item> SHTUXITE_SOUL = REGISTRY.register("shtuxite_soul", () -> new ShtuxiteSoulItem());
	public static final RegistryObject<Item> LORE_SHTQ_7V_3 = REGISTRY.register("lore_shtq_7v_3", () -> new LoreShtq7v3Item());
	public static final RegistryObject<Item> CHTUXLAGOR_PIECE = REGISTRY.register("chtuxlagor_piece", () -> new ChtuxlagorPieceItem());
	public static final RegistryObject<Item> CATSTEEL_BLOCK = block(ShtundexModBlocks.CATSTEEL_BLOCK);
	public static final RegistryObject<Item> BERRY_PIE = REGISTRY.register("berry_pie", () -> new BerryPieItem());
	public static final RegistryObject<Item> FLOUR = REGISTRY.register("flour", () -> new FlourItem());
	public static final RegistryObject<Item> CATSTEEL_APPLE = REGISTRY.register("catsteel_apple", () -> new CatsteelAppleItem());
	public static final RegistryObject<Item> CATSTEEL_COIN = REGISTRY.register("catsteel_coin", () -> new CatsteelCoinItem());
	public static final RegistryObject<Item> CRATE = block(ShtundexModBlocks.CRATE);
	public static final RegistryObject<Item> COIN_PRESS_SCHEME = REGISTRY.register("coin_press_scheme", () -> new CoinPressSchemeItem());
	public static final RegistryObject<Item> CATSTEEL_NUGGET = REGISTRY.register("catsteel_nugget", () -> new CatsteelNuggetItem());
	public static final RegistryObject<Item> SWORDLAND = REGISTRY.register("swordland", () -> new SwordlandItem());
	public static final RegistryObject<Item> CHTUXLAGOR_BLESSING_CURIOS = REGISTRY.register("chtuxlagor_blessing_curios", () -> new ChtuxlagorBlessingCuriosItem());
	public static final RegistryObject<Item> SHTUNDEX_WORLD_BLESSING = REGISTRY.register("shtundex_world_blessing", () -> new ShtundexWorldBlessingItem());
	public static final RegistryObject<Item> PLATE_PRESS = REGISTRY.register("plate_press", () -> new PlatePressItem());
	public static final RegistryObject<Item> PRESS = block(ShtundexModBlocks.PRESS);
	public static final RegistryObject<Item> CATSTEEL_WORKBENCH_BLOCK = block(ShtundexModBlocks.CATSTEEL_WORKBENCH_BLOCK);
	public static final RegistryObject<Item> TIN_ORE = block(ShtundexModBlocks.TIN_ORE);
	public static final RegistryObject<Item> TIN_BLOCK = block(ShtundexModBlocks.TIN_BLOCK);
	public static final RegistryObject<Item> TIN_INGOT = REGISTRY.register("tin_ingot", () -> new TinIngotItem());
	public static final RegistryObject<Item> TIN_DUST = REGISTRY.register("tin_dust", () -> new TinDustItem());
	public static final RegistryObject<Item> COPPER_DUST = REGISTRY.register("copper_dust", () -> new CopperDustItem());
	public static final RegistryObject<Item> BRONZE_DUST = REGISTRY.register("bronze_dust", () -> new BronzeDustItem());
	public static final RegistryObject<Item> MACERATOR = block(ShtundexModBlocks.MACERATOR);
	public static final RegistryObject<Item> DEEPSLATE_TIN_ORE = block(ShtundexModBlocks.DEEPSLATE_TIN_ORE);
	public static final RegistryObject<Item> BRONZE_INGOT = REGISTRY.register("bronze_ingot", () -> new BronzeIngotItem());
	public static final RegistryObject<Item> CATSTEEL_DUST = REGISTRY.register("catsteel_dust", () -> new CatsteelDustItem());
	public static final RegistryObject<Item> GRINDING_BALL = REGISTRY.register("grinding_ball", () -> new GrindingBallItem());
	public static final RegistryObject<Item> RAW_TIN = REGISTRY.register("raw_tin", () -> new RawTinItem());
	public static final RegistryObject<Item> WRENCH = REGISTRY.register("wrench", () -> new WrenchItem());
	public static final RegistryObject<Item> CATSTEEL_GRENERATOR = block(ShtundexModBlocks.CATSTEEL_GRENERATOR);
	public static final RegistryObject<Item> CATSTEEL_PILL = REGISTRY.register("catsteel_pill", () -> new CatsteelPillItem());
	public static final RegistryObject<Item> DEPELLETED_CATSTEEL = REGISTRY.register("depelleted_catsteel", () -> new DepelletedCatsteelItem());
	public static final RegistryObject<Item> IRON_DUST = REGISTRY.register("iron_dust", () -> new IronDustItem());
	public static final RegistryObject<Item> GOLD_DUST = REGISTRY.register("gold_dust", () -> new GoldDustItem());
	public static final RegistryObject<Item> URANIUM_ORE = block(ShtundexModBlocks.URANIUM_ORE);
	public static final RegistryObject<Item> URANIUM_BLOCK = block(ShtundexModBlocks.URANIUM_BLOCK);
	public static final RegistryObject<Item> URANIUM_INGOT = REGISTRY.register("uranium_ingot", () -> new UraniumIngotItem());
	public static final RegistryObject<Item> DEEPSLATE_URANIUM_ORE = block(ShtundexModBlocks.DEEPSLATE_URANIUM_ORE);
	public static final RegistryObject<Item> URANIUM_DUST = REGISTRY.register("uranium_dust", () -> new UraniumDustItem());
	public static final RegistryObject<Item> RAW_URANIUM = REGISTRY.register("raw_uranium", () -> new RawUraniumItem());
	public static final RegistryObject<Item> LEAD_ORE = block(ShtundexModBlocks.LEAD_ORE);
	public static final RegistryObject<Item> LEAD_BLOCK = block(ShtundexModBlocks.LEAD_BLOCK);
	public static final RegistryObject<Item> LEAD_INGOT = REGISTRY.register("lead_ingot", () -> new LeadIngotItem());
	public static final RegistryObject<Item> RAW_LEAD = REGISTRY.register("raw_lead", () -> new RawLeadItem());
	public static final RegistryObject<Item> DEEPSLATE_LEAD_ORE = block(ShtundexModBlocks.DEEPSLATE_LEAD_ORE);
	public static final RegistryObject<Item> LEAD_DUST = REGISTRY.register("lead_dust", () -> new LeadDustItem());
	public static final RegistryObject<Item> ANTIRAD_CLOTH = REGISTRY.register("antirad_cloth", () -> new AntiradClothItem());
	public static final RegistryObject<Item> HAZMAT_HELMET = REGISTRY.register("hazmat_helmet", () -> new HazmatItem.Helmet());
	public static final RegistryObject<Item> HAZMAT_CHESTPLATE = REGISTRY.register("hazmat_chestplate", () -> new HazmatItem.Chestplate());
	public static final RegistryObject<Item> HAZMAT_LEGGINGS = REGISTRY.register("hazmat_leggings", () -> new HazmatItem.Leggings());
	public static final RegistryObject<Item> HAZMAT_BOOTS = REGISTRY.register("hazmat_boots", () -> new HazmatItem.Boots());
	public static final RegistryObject<Item> LEAD_PLATE = REGISTRY.register("lead_plate", () -> new LeadPlateItem());
	public static final RegistryObject<Item> GEIGER_COUNT = REGISTRY.register("geiger_count", () -> new GeigerCountItem());
	public static final RegistryObject<Item> CIRCUIT = REGISTRY.register("circuit", () -> new CircuitItem());
	public static final RegistryObject<Item> UNFINISHED_CATSTEEL_CIRCUIT = REGISTRY.register("unfinished_catsteel_circuit", () -> new UnfinishedCatsteelCircuitItem());
	public static final RegistryObject<Item> CIRCUIT_PRSSS = REGISTRY.register("circuit_prsss", () -> new CircuitPrsssItem());
	public static final RegistryObject<Item> CATSTEEL_STIMULANTS = REGISTRY.register("catsteel_stimulants", () -> new CatsteelStimulantsItem());
	public static final RegistryObject<Item> CHTUXLAGOR_MANTLE_CHESTPLATE = REGISTRY.register("chtuxlagor_mantle_chestplate", () -> new ChtuxlagorMantleItem.Chestplate());
	public static final RegistryObject<Item> COAL_DUST = REGISTRY.register("coal_dust", () -> new CoalDustItem());
	public static final RegistryObject<Item> NANOFIBER_CLOTH = REGISTRY.register("nanofiber_cloth", () -> new NanofiberClothItem());
	public static final RegistryObject<Item> NANOSABER = REGISTRY.register("nanosaber", () -> new NanosaberItem());
	public static final RegistryObject<Item> NANOSABER_ACTIVE = REGISTRY.register("nanosaber_active", () -> new NanosaberActiveItem());
	public static final RegistryObject<Item> DIAMOND_DUST = REGISTRY.register("diamond_dust", () -> new DiamondDustItem());
	public static final RegistryObject<Item> NANO_HELMET = REGISTRY.register("nano_helmet", () -> new NanoItem.Helmet());
	public static final RegistryObject<Item> NANO_CHESTPLATE = REGISTRY.register("nano_chestplate", () -> new NanoItem.Chestplate());
	public static final RegistryObject<Item> NANO_LEGGINGS = REGISTRY.register("nano_leggings", () -> new NanoItem.Leggings());
	public static final RegistryObject<Item> NANO_BOOTS = REGISTRY.register("nano_boots", () -> new NanoItem.Boots());
	public static final RegistryObject<Item> ENERGY_CRYSTAL = REGISTRY.register("energy_crystal", () -> new EnergyCrystalItem());
	public static final RegistryObject<Item> SHTUXIAN_KIT = REGISTRY.register("shtuxian_kit", () -> new ShtuxianKitItem());
	public static final RegistryObject<Item> CHTUXLAGOR_KIT = REGISTRY.register("chtuxlagor_kit", () -> new ChtuxlagorKitItem());
	public static final RegistryObject<Item> CATSTEEL_SHIELD = REGISTRY.register("catsteel_shield", () -> new CatsteelShieldItem());
	public static final RegistryObject<Item> CATSTEEL_RING = REGISTRY.register("catsteel_ring", () -> new CatsteelRingItem());
	public static final RegistryObject<Item> CHALK_RITUAL = block(ShtundexModBlocks.CHALK_RITUAL);
	public static final RegistryObject<Item> CHALK = REGISTRY.register("chalk", () -> new ChalkItem());
	public static final RegistryObject<Item> VAMPIRIC_AMULET = REGISTRY.register("vampiric_amulet", () -> new VampiricAmuletItem());
	public static final RegistryObject<Item> TRAVELER_BOOTS = REGISTRY.register("traveler_boots", () -> new TravelerBootsItem());
	public static final RegistryObject<Item> CAT_CORE = REGISTRY.register("cat_core", () -> new CatCoreItem());
	public static final RegistryObject<Item> VAMPIRE_SPAWN_EGG = REGISTRY.register("vampire_spawn_egg", () -> new ForgeSpawnEggItem(ShtundexModEntities.VAMPIRE, -13421773, -3407872, new Item.Properties()));
	public static final RegistryObject<Item> HUMAN_SPAWN_EGG = REGISTRY.register("human_spawn_egg", () -> new ForgeSpawnEggItem(ShtundexModEntities.HUMAN, -16724788, -16777012, new Item.Properties()));
	public static final RegistryObject<Item> SHTUK_SPAWN_EGG = REGISTRY.register("shtuk_spawn_egg", () -> new ForgeSpawnEggItem(ShtundexModEntities.SHTUK, -16738048, -16724890, new Item.Properties()));
	public static final RegistryObject<Item> NETHERITE_GEAR_TRUE = REGISTRY.register("netherite_gear_true", () -> new NetheriteGearTrueItem());
	public static final RegistryObject<Item> IRON_GEAR = REGISTRY.register("iron_gear", () -> new IronGearItem());
	public static final RegistryObject<Item> MACHINE_CASING = block(ShtundexModBlocks.MACHINE_CASING);
	public static final RegistryObject<Item> NETHERITE_CIRCUIT = REGISTRY.register("netherite_circuit", () -> new NetheriteCircuitItem());
	public static final RegistryObject<Item> UNFINISHED_NETHERITE_CIRCUIT = REGISTRY.register("unfinished_netherite_circuit", () -> new UnfinishedNetheriteCircuitItem());
	public static final RegistryObject<Item> IRRADIATED_SLIME_SPAWN_EGG = REGISTRY.register("irradiated_slime_spawn_egg", () -> new ForgeSpawnEggItem(ShtundexModEntities.IRRADIATED_SLIME, -6711040, -10053376, new Item.Properties()));
	public static final RegistryObject<Item> XENOMITE_SHARD = REGISTRY.register("xenomite_shard", () -> new XenomiteShardItem());
	public static final RegistryObject<Item> REFINED_XENIUM_PLATE = REGISTRY.register("refined_xenium_plate", () -> new RefinedXeniumPlateItem());
	public static final RegistryObject<Item> DARK_STEEL_INGOT = REGISTRY.register("dark_steel_ingot", () -> new DarkSteelIngotItem());
	public static final RegistryObject<Item> OBSIDIAN_DUST = REGISTRY.register("obsidian_dust", () -> new ObsidianDustItem());
	public static final RegistryObject<Item> DARK_STEEL_DUST = REGISTRY.register("dark_steel_dust", () -> new DarkSteelDustItem());
	public static final RegistryObject<Item> DARK_ARMOR_HELMET = REGISTRY.register("dark_armor_helmet", () -> new DarkArmorItem.Helmet());
	public static final RegistryObject<Item> DARK_ARMOR_CHESTPLATE = REGISTRY.register("dark_armor_chestplate", () -> new DarkArmorItem.Chestplate());
	public static final RegistryObject<Item> DARK_ARMOR_LEGGINGS = REGISTRY.register("dark_armor_leggings", () -> new DarkArmorItem.Leggings());
	public static final RegistryObject<Item> DARK_ARMOR_BOOTS = REGISTRY.register("dark_armor_boots", () -> new DarkArmorItem.Boots());
	public static final RegistryObject<Item> DARK_PICKAXE = REGISTRY.register("dark_pickaxe", () -> new DarkPickaxeItem());
	public static final RegistryObject<Item> DARK_AXE = REGISTRY.register("dark_axe", () -> new DarkAxeItem());
	public static final RegistryObject<Item> DARK_SWORD = REGISTRY.register("dark_sword", () -> new DarkSwordItem());
	public static final RegistryObject<Item> PIZZA = REGISTRY.register("pizza", () -> new PizzaItem());
	public static final RegistryObject<Item> CATSTEEL_STAFF = REGISTRY.register("catsteel_staff", () -> new CatsteelStaffItem());
	public static final RegistryObject<Item> ARMOR_RECHARGE_MODULE = REGISTRY.register("armor_recharge_module", () -> new ArmorRechargeModuleItem());
	public static final RegistryObject<Item> PIZZA_BOX = REGISTRY.register("pizza_box", () -> new PizzaBoxItem());
	public static final RegistryObject<Item> TINY_CHTUXLAGOR_SHARD = REGISTRY.register("tiny_chtuxlagor_shard", () -> new TinyChtuxlagorShardItem());
	public static final RegistryObject<Item> CRIMSON_ORE = block(ShtundexModBlocks.CRIMSON_ORE);
	public static final RegistryObject<Item> CORRUPTED_ORE = block(ShtundexModBlocks.CORRUPTED_ORE);
	public static final RegistryObject<Item> CRIMSON_INGOT = REGISTRY.register("crimson_ingot", () -> new CrimsonIngotItem());
	public static final RegistryObject<Item> WARPED_INGOT = REGISTRY.register("warped_ingot", () -> new WarpedIngotItem());
	public static final RegistryObject<Item> WARPED_ARMOR_HELMET = REGISTRY.register("warped_armor_helmet", () -> new WarpedArmorItem.Helmet());
	public static final RegistryObject<Item> WARPED_ARMOR_CHESTPLATE = REGISTRY.register("warped_armor_chestplate", () -> new WarpedArmorItem.Chestplate());
	public static final RegistryObject<Item> WARPED_ARMOR_LEGGINGS = REGISTRY.register("warped_armor_leggings", () -> new WarpedArmorItem.Leggings());
	public static final RegistryObject<Item> WARPED_ARMOR_BOOTS = REGISTRY.register("warped_armor_boots", () -> new WarpedArmorItem.Boots());
	public static final RegistryObject<Item> CRIMSON_ARMOR_HELMET = REGISTRY.register("crimson_armor_helmet", () -> new CrimsonArmorItem.Helmet());
	public static final RegistryObject<Item> CRIMSON_ARMOR_CHESTPLATE = REGISTRY.register("crimson_armor_chestplate", () -> new CrimsonArmorItem.Chestplate());
	public static final RegistryObject<Item> CRIMSON_ARMOR_LEGGINGS = REGISTRY.register("crimson_armor_leggings", () -> new CrimsonArmorItem.Leggings());
	public static final RegistryObject<Item> CRIMSON_ARMOR_BOOTS = REGISTRY.register("crimson_armor_boots", () -> new CrimsonArmorItem.Boots());
	public static final RegistryObject<Item> NETHERITE_FORCE = REGISTRY.register("netherite_force", () -> new NetheriteForceItem());
	public static final RegistryObject<Item> GOLDEN_FORCE = REGISTRY.register("golden_force", () -> new GoldenForceItem());
	public static final RegistryObject<Item> CRIMSON_FORCE = REGISTRY.register("crimson_force", () -> new CrimsonForceItem());
	public static final RegistryObject<Item> CATSTEEL_FORCE = REGISTRY.register("catsteel_force", () -> new CatsteelForceItem());
	public static final RegistryObject<Item> CHTUXLAGOR_FORCE = REGISTRY.register("chtuxlagor_force", () -> new ChtuxlagorForceItem());
	public static final RegistryObject<Item> DIAMOND_FORCE = REGISTRY.register("diamond_force", () -> new DiamondForceItem());
	public static final RegistryObject<Item> MINER_FORCE = REGISTRY.register("miner_force", () -> new MinerForceItem());
	public static final RegistryObject<Item> SHTUXIBUS_FORCE = REGISTRY.register("shtuxibus_force", () -> new ShtuxibusForceItem());
	public static final RegistryObject<Item> SHT_Q_7_FORCE = REGISTRY.register("sht_q_7_force", () -> new ShtQ7ForceItem());
	public static final RegistryObject<Item> WARPED_FORCE = REGISTRY.register("warped_force", () -> new WarpedForceItem());
	public static final RegistryObject<Item> CRIMSON_PICKAXE = REGISTRY.register("crimson_pickaxe", () -> new CrimsonPickaxeItem());
	public static final RegistryObject<Item> CRIMSON_AXE = REGISTRY.register("crimson_axe", () -> new CrimsonAxeItem());
	public static final RegistryObject<Item> CRIMSON_SWORD = REGISTRY.register("crimson_sword", () -> new CrimsonSwordItem());
	public static final RegistryObject<Item> CRIMSON_SHOVEL = REGISTRY.register("crimson_shovel", () -> new CrimsonShovelItem());
	public static final RegistryObject<Item> WARPED_PICKAXE = REGISTRY.register("warped_pickaxe", () -> new WarpedPickaxeItem());
	public static final RegistryObject<Item> WARPED_AXE = REGISTRY.register("warped_axe", () -> new WarpedAxeItem());
	public static final RegistryObject<Item> WARPED_SWORD = REGISTRY.register("warped_sword", () -> new WarpedSwordItem());
	public static final RegistryObject<Item> WARPED_SHOVEL = REGISTRY.register("warped_shovel", () -> new WarpedShovelItem());
	public static final RegistryObject<Item> EMERALD_FORCE = REGISTRY.register("emerald_force", () -> new EmeraldForceItem());
	public static final RegistryObject<Item> TIN_FORCE = REGISTRY.register("tin_force", () -> new TinForceItem());
	public static final RegistryObject<Item> COPPER_FORCE = REGISTRY.register("copper_force", () -> new CopperForceItem());
	public static final RegistryObject<Item> INFINITY_MODE_CHANGER = REGISTRY.register("infinity_mode_changer", () -> new InfinityModeChangerItem());
	public static final RegistryObject<Item> LORE_AWAKENING = REGISTRY.register("lore_awakening", () -> new LoreAwakeningItem());
	public static final RegistryObject<Item> LAPIS_FORCE = REGISTRY.register("lapis_force", () -> new LapisForceItem());
	public static final RegistryObject<Item> MATERIAL_FORCE = REGISTRY.register("material_force", () -> new MaterialForceItem());
	public static final RegistryObject<Item> BOSS_ALTAR = block(ShtundexModBlocks.BOSS_ALTAR);
	public static final RegistryObject<Item> BOSS_ARENA_BLOCK = block(ShtundexModBlocks.BOSS_ARENA_BLOCK);
	public static final RegistryObject<Item> TRERRAFORMING_DIRT_STAFF = REGISTRY.register("trerraforming_dirt_staff", () -> new TrerraformingDirtStaffItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
